# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui2.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1244, 689)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(30, 60, 501, 391))
        self.textEdit.setObjectName("textEdit")
        self.fileBrowseButton = QtWidgets.QPushButton(self.centralwidget)
        self.fileBrowseButton.setGeometry(QtCore.QRect(30, 480, 93, 28))
        self.fileBrowseButton.setObjectName("fileBrowseButton")
        self.summarizeButton = QtWidgets.QPushButton(self.centralwidget)
        self.summarizeButton.setGeometry(QtCore.QRect(30, 550, 501, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.summarizeButton.setFont(font)
        self.summarizeButton.setObjectName("summarizeButton")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(640, 60, 571, 391))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.labelInput = QtWidgets.QLabel(self.centralwidget)
        self.labelInput.setGeometry(QtCore.QRect(30, 15, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelInput.setFont(font)
        self.labelInput.setObjectName("labelInput")
        self.textResetButton = QtWidgets.QPushButton(self.centralwidget)
        self.textResetButton.setGeometry(QtCore.QRect(440, 480, 93, 28))
        self.textResetButton.setObjectName("textResetButton")
        self.copyTextButton = QtWidgets.QPushButton(self.centralwidget)
        self.copyTextButton.setGeometry(QtCore.QRect(1120, 470, 93, 28))
        self.copyTextButton.setObjectName("copyTextButton")
        self.processLabel = QtWidgets.QLabel(self.centralwidget)
        self.processLabel.setGeometry(QtCore.QRect(650, 550, 441, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.processLabel.setFont(font)
        self.processLabel.setObjectName("processLabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1244, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuModel = QtWidgets.QMenu(self.menubar)
        self.menuModel.setObjectName("menuModel")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionExtractive = QtWidgets.QAction(MainWindow)
        self.actionExtractive.setObjectName("actionExtractive")
        self.actionAbstractive = QtWidgets.QAction(MainWindow)
        self.actionAbstractive.setObjectName("actionAbstractive")
        self.actionHybrid = QtWidgets.QAction(MainWindow)
        self.actionHybrid.setObjectName("actionHybrid")
        self.menuFile.addAction(self.actionOpen)
        self.menuModel.addAction(self.actionExtractive)
        self.menuModel.addAction(self.actionAbstractive)
        self.menuModel.addAction(self.actionHybrid)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuModel.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.fileBrowseButton.setText(_translate("MainWindow", "Open TXT file"))
        self.summarizeButton.setText(_translate("MainWindow", "Summarize"))
        self.labelInput.setText(_translate("MainWindow", "Enter your text here"))
        self.textResetButton.setText(_translate("MainWindow", "Reset"))
        self.copyTextButton.setText(_translate("MainWindow", "copy text"))
        self.processLabel.setText(_translate("MainWindow", "TextLabel"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuModel.setTitle(_translate("MainWindow", "Model"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionExtractive.setText(_translate("MainWindow", "Extractive"))
        self.actionAbstractive.setText(_translate("MainWindow", "Abstractive"))
        self.actionHybrid.setText(_translate("MainWindow", "Hybrid"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
